# =============================================================================
# Phase 4 - AWS Glue Crawler
# =============================================================================
# This file creates a Glue Crawler to automatically discover schema and
# partitions from the landing zone Parquet files generated by Phase 3 Flink.
# =============================================================================

# -----------------------------------------------------------------------------
# AWS Glue Crawler - Landing Zone Discovery
# -----------------------------------------------------------------------------

resource "aws_glue_crawler" "landing_zone" {
  name          = local.glue_crawler_name
  role          = aws_iam_role.glue.arn
  database_name = aws_glue_catalog_database.chargeback_data.name
  description   = "Discovers schema and partitions from landing zone Parquet files"
  
  # S3 target - landing zone path
  s3_target {
    path = local.landing_zone_s3_path
    
    # Exclusions (if needed to skip temp files)
    exclusions = [
      "**/_temporary/**",
      "**/.spark/**",
      "**/_SUCCESS",
      "**/.*.crc"
    ]
  }
  
  # Schema change policy
  schema_change_policy {
    delete_behavior = "LOG" # Log deletions but don't delete from catalog
    update_behavior = "UPDATE_IN_DATABASE" # Update schema when changes detected
  }
  
  # Recrawl policy (how to handle existing data)
  recrawl_policy {
    recrawl_behavior = "CRAWL_NEW_FOLDERS_ONLY"
    # Only crawl new partitions, don't rescan everything (faster)
    # Alternative: CRAWL_EVERYTHING (slower but ensures accuracy)
  }
  
  # Table prefix (tables will be named: landing_chargebacks)
  table_prefix = var.glue_crawler_table_prefix
  
  # Configuration for crawler behavior
  configuration = jsonencode({
    Version = 1.0
    CrawlerOutput = {
      Partitions = {
        AddOrUpdateBehavior = "InheritFromTable"
      }
      Tables = {
        AddOrUpdateBehavior = "MergeNewColumns"
      }
    }
    Grouping = {
      TableGroupingPolicy = "CombineCompatibleSchemas"
    }
  })
  
  # Schedule (runs before ETL jobs to ensure catalog is updated)
  # For 4 executions/day: runs at 00:00, 06:00, 12:00, 18:00
  # ETL runs 30 minutes later at 00:30, 06:30, 12:30, 18:30
  schedule = var.glue_crawler_schedule
  
  tags = merge(
    local.common_tags,
    {
      Name = local.glue_crawler_name
    }
  )
  
  # Ensure database exists first
  depends_on = [
    aws_glue_catalog_database.chargeback_data,
    aws_iam_role_policy_attachment.glue_service_policy
  ]
}

# -----------------------------------------------------------------------------
# CloudWatch Log Group for Crawler
# -----------------------------------------------------------------------------

resource "aws_cloudwatch_log_group" "glue_crawler" {
  name              = local.glue_crawler_log_group
  retention_in_days = 7 # Keep logs for 7 days
  
  tags = merge(
    local.common_tags,
    {
      Name = "${local.glue_crawler_name}-logs"
    }
  )
}

# -----------------------------------------------------------------------------
# CloudWatch Alarms for Crawler Failures
# -----------------------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "crawler_failure" {
  count = var.enable_cloudwatch_alarms ? 1 : 0
  
  alarm_name          = "${local.glue_crawler_name}-failure"
  alarm_description   = "Glue crawler failed to complete successfully"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "glue.driver.aggregate.numFailedTasks"
  namespace           = "Glue"
  period              = 300 # 5 minutes
  statistic           = "Sum"
  threshold           = 0
  treat_missing_data  = "notBreaching"
  
  dimensions = {
    JobName = local.glue_crawler_name
    Type    = "count"
  }
  
  alarm_actions = var.alarm_email_endpoints != [] ? [aws_sns_topic.glue_alerts[0].arn] : []
  
  tags = merge(
    local.common_tags,
    {
      Name = "${local.glue_crawler_name}-failure-alarm"
    }
  )
}

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------

output "glue_crawler_name" {
  description = "Name of the Glue crawler"
  value       = aws_glue_crawler.landing_zone.name
}

output "glue_crawler_arn" {
  description = "ARN of the Glue crawler"
  value       = aws_glue_crawler.landing_zone.arn
}

output "glue_crawler_schedule" {
  description = "Schedule expression for the crawler"
  value       = aws_glue_crawler.landing_zone.schedule
}
